[default]
db.mongodb_uri = "mongodb://localhost:27017"
pulsar.url = "http://localhost:8913"
pulsar.status.poll_interval = 4
pulsar.status.max_polls = 100

logging.level = "DEBUG"
logging.output_json = false

oauth.enable = false
basic_auth.enable = false
basic_auth.username = "user"
basic_auth.password = "password"

[dev-docker]
db.mongodb_uri = "mongodb://tesp-db:27017"
pulsar.url = "http://localhost:8913"
logging.output_json = false
