[default]
db.mongodb_uri = "mongodb://localhost:27017"
pulsar.url = "http://localhost:8913"
pulsar.status.poll_interval = 4
pulsar.status.max_polls = 400
pulsar.client_timeout = 30

logging.level = "DEBUG"
logging.output_json = false

oauth.enable = false
# OAuth2 Configuration
# IMPORTANT: Only tokens from these issuers will be accepted
# At least one issuer must be configured when oauth.enable = true
oauth.allowed_issuers = []
oauth.required_audience = "tesp-api"
oauth.cache_jwks_ttl = 300  # Cache JWKS for 5 minutes (in seconds)

basic_auth.enable = false
basic_auth.username = ""
basic_auth.password = ""

[dev-docker]
db.mongodb_uri = "mongodb://tesp-db:27017"
pulsar.url = "http://pulsar_rest:8913"
logging.output_json = false
